export const ICONS = {
    down:           require("../assets/icons/arrow_Down.png"),
    up:             require("../assets/icons/arrow_Up.png"),
    left:           require("../assets/icons/arrow_Left.png"),
    right:          require("../assets/icons/arrow_Right.png"),
    bag:            require("../assets/icons/bag.png"),
    bean:           require("../assets/icons/bean.png"),
    calling:        require("../assets/icons/calling.png"),
    discount:       require("../assets/icons/discount.png"),
    filter:         require("../assets/icons/filter.png"),
    gps:            require("../assets/icons/gps.png"),
    favorites:      require("../assets/icons/heart.png"),
    home:           require("../assets/icons/home.png"),
    heart:          require("../assets/icons/heart.png"),
    milk:           require("../assets/icons/milk.png"),
    minusCircle:    require("../assets/icons/minus_Circle.png"),
    moreCircle:     require("../assets/icons/more_Circle.png"),
    motorBike:      require("../assets/icons/motor_Bike.png"),
    notification:   require("../assets/icons/notification.png"),
    plusCircle:     require("../assets/icons/plus_Circle.png"),
    plus:           require("../assets/icons/plus.png"),
    search:         require("../assets/icons/search.png"),
    star:           require("../assets/icons/star.png"),
    wallet:         require("../assets/icons/wallet.png"),
}

export const IMG = {
    //Bebidas
    cajuina:        require("../assets/images/BEBIDA-cajuina.png"),   
    caldoCana:      require("../assets/images/BEBIDA-caldodecana.png"),
    bacuri:         require("../assets/images/BEBIDA-sucobacuri.png"),
    caja:           require("../assets/images/BEBIDA-sucocaja.png"),
    caju:           require("../assets/images/BEBIDA-sucocaju.png"),
    //Lanche
    boloFrito:      require("../assets/images/LANCHES-bolofrito.png"),
    boloGoma:       require("../assets/images/LANCHES-bologoma.png"),
    boloMacaxeira:  require("../assets/images/LANCHES-bolomacaxeira.png"),
    bomba:          require("../assets/images/LANCHES-bomba.png"),
    coxinhaCarne:   require("../assets/images/LANCHES-coxinhacarne.png"),
    cuscuz:         require("../assets/images/LANCHES-cuscuz.png"),
    cuscuzCarne:    require("../assets/images/LANCHES-cuscuzcarnequeijo.png"),
    //Sobremesa
    boloTapioca:    require("../assets/images/SOBREMESA-bolotapioca.png"),
    doceCaju:       require("../assets/images/SOBREMESA-docecaju.png"),
    mungunzaDoce:   require("../assets/images/SOBREMESA-mungunzadoce.png"),
    tapioca:        require("../assets/images/SOBREMESA-tapioca.png"),
}